### ISSUE TITLE
The assembly name in the CopyMe.PlatzDataService.tt.txt file is pointing to a non-existing path

### ISSUE THREAD

**Issue by ashkonda** [ProCodersPtyLtd/MasterDetailsDataEntry#76]
The assembly name in line 3 in the CopyMe.PlatzDataService.tt.txt file is pointing to $(SolutionDir)Platz.ObjectBuilder.Templates\bin\Debug\Platz.ObjectBuilder.Templates.dll, which doesn't exist.
This causes the error below. 
The demo app is using <#@ include file="$(PlatzObjectBuilderTemplateDirectory)PlatzDataService.Tools.ttinclude" #> instead.

An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.IO.FileNotFoundException: Could not find a part of the path 'C:\Sandbox\DemoSqlForms\Platz.ObjectBuilder.Templates\bin\Debug\Platz.ObjectBuilder.Templates.dll'.
File name: 'C:\Sandbox\DemoSqlForms\Platz.ObjectBuilder.Templates\bin\Debug\Platz.ObjectBuilder.Templates.dll' ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Sandbox\DemoSqlForms\Platz.ObjectBuilder.Templates\bin\Debug\Platz.ObjectBuilder.Templates.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.<>c.<.ctor>b__15_0(String x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilation()
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable`1 references, Boolean debug, SupportedLanguage language, String compilerOptions)

**Comment by euklad** [comment]
Thanks for your feedback, @ashkonda.
Yes you're right the package 0.2.1 contains an old CopyMe.PlatzDataService.tt.txt file that points to nowhere.
Please update nuget reference to Platz.SqlForms to version 0.2.2 or later to solve this issue.
If issue still persists, please let us know.
Cheers,
Ev

**Comment by euklad** [comment]
We don't hear from you for a long time, so we assume that issue is resolved and can be closed.
Thanks for your cooperation.
